DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS Document;
DROP TABLE IF EXISTS Language;
DROP TABLE IF EXISTS File;
DROP TABLE IF EXISTS DocAttribute;
DROP TABLE IF EXISTS Type;
DROP TABLE IF EXISTS Worker;
DROP TABLE IF EXISTS CompanyRole;
DROP TABLE IF EXISTS Revision;
DROP TABLE IF EXISTS RevisionAttribute;
DROP TABLE IF EXISTS Stated;
DROP TABLE IF EXISTS DocPossesses;
DROP TABLE IF EXISTS RevPossesses;
DROP TABLE IF EXISTS Belongs;
DROP TABLE IF EXISTS Modified;
DROP TABLE IF EXISTS Request;
DROP TABLE IF EXISTS ProjectRole;
DROP TABLE IF EXISTS WorkerHasProjRole; --NOVO! TERNÁRIA PROJ ROLE
DROP TABLE IF EXISTS CheckOut;
DROP TABLE IF EXISTS CheckIn;
DROP TABLE IF EXISTS Status; --NOVO! ADICIONAR NOS PONTOS ANTERIORES

CREATE TABLE Company (
	CID		INTEGER,
	Cname 		VARCHAR2(50),
	NIF		INTEGER,
	address		TEXT,
	CONSTRAINT company_pk PRIMARY KEY (CID)
);
CREATE TABLE Document (
	docID		INTEGER PRIMARY KEY,
	dNAME		VARCHAR2(50) NOT NULL,
	date_ini	DATE,
	date_fin	DATE,
	type		VARCHAR2(50),
	ownerID		INTEGER,
	CONSTRAINT document_type_fk FOREIGN KEY (type) REFERENCES Type(TID),
	CONSTRAINT document_owner_fk FOREIGN KEY (ownerID) REFERENCES Worker(WID),
	CONSTRAINT checkDiDf CHECK(date_ini<date_fin OR date_fin=NULL)
);
CREATE TABLE Language (
	LID			INTEGER,
	Lname		VARCHAR2(50),
	CONSTRAINT language_pk PRIMARY KEY (LID)
);
CREATE TABLE File (
	Fname		VARCHAR2(50),
	size		INTEGER,
	extension	TEXT,
	docID		INTEGER,
	CONSTRAINT file_pk PRIMARY KEY (Fname), 
	CONSTRAINT file_doc_fk FOREIGN KEY (docID) REFERENCES Document(docID),
	CONSTRAINT checkFSize CHECK(size >=0)
);
CREATE TABLE DocAttribute (
	DAID	INTEGER,
	DAname	VARCHAR2(50),
	DAvalue	TEXT,
	CONSTRAINT docAttribute_pk PRIMARY KEY (DAID) 
);
CREATE TABLE Type (
	TID			INTEGER,
	Tname		VARCHAR2(50),
	last_mod_date	DATE,
	status		TEXT,
	remarks		TEXT,
	CONSTRAINT type_pk PRIMARY KEY (TID)
);
CREATE TABLE Worker (
	WID		INTEGER PRIMARY KEY,
	Wname		TEXT NOT NULL
);
CREATE TABLE CompanyRole (
	CRID	INTEGER,
	CRname	VARCHAR2(50),
	CONSTRAINT companyRole_pk PRIMARY KEY (CRID)
);
CREATE TABLE Revision (
	docID		INTEGER,
	revID		INTEGER,	
	version		TEXT,
	date		DATE,
	CONSTRAINT revision_fk FOREIGN KEY (docID) REFERENCES Document(docID),
	CONSTRAINT revision_pk PRIMARY KEY (revID)
);
CREATE TABLE RevisionAttribute (
	RAID		INTEGER,
	RAname		TEXT,
	RAvalue		TEXT,
	CONSTRAINT revisionAttribute_pk PRIMARY KEY (RAID)
);
CREATE TABLE Stated (
	LID			INTEGER,
	docID		INTEGER,
	CONSTRAINT stated_fk1 FOREIGN KEY (LID) REFERENCES Language(LID),
	CONSTRAINT stated_fk2 FOREIGN KEY (docID) REFERENCES Document(docID),
	CONSTRAINT stated_pk PRIMARY KEY(LID,docID)
);
CREATE TABLE DocPossesses (
	DAID		INTEGER,
	docID		INTEGER,
	CONSTRAINT docPossesses_fk1 FOREIGN KEY (DAID) REFERENCES DocAttribute(DAID),
	CONSTRAINT docPossesses_fk2 FOREIGN KEY (docID) REFERENCES Document(docID),
	CONSTRAINT docPossesses_pk PRIMARY KEY(DAID,docID)
);
CREATE TABLE RevPossesses (
	RAID 		INTEGER,
	revID		INTEGER,
	CONSTRAINT revPossesses_fk1 FOREIGN KEY (RAID) REFERENCES RevAttribute(RAID),
	CONSTRAINT revPossesses_fk2 FOREIGN KEY (revID) REFERENCES Revision(revID),
	CONSTRAINT revPossesses_pk PRIMARY KEY(revID,RAID)
);
CREATE TABLE Belongs (
	WID		INTEGER,
	CRID		INTEGER,
	CONSTRAINT belongs_fk1 FOREIGN KEY (WID) REFERENCES Worker(WID),
	CONSTRAINT belongs_fk2 FOREIGN KEY (CRID) REFERENCES CompanyRole(CRID),
	CONSTRAINT belongs_pk PRIMARY KEY(WID,CRID)
);
CREATE TABLE Modified (
	Tname		VARCHAR2(50),
	WID		INTEGER,
	CONSTRAINT modified_fk1 FOREIGN KEY (Tname) REFERENCES Type(Tname),
	CONSTRAINT modified_fk2 FOREIGN KEY (WID) REFERENCES Worker(WID),
	CONSTRAINT modified_pk PRIMARY KEY(Tname,WID)
);
CREATE TABLE Request (
	docID		INTEGER,
	CID			INTEGER,
	SID			INTEGER,
	propose_date	DATE NOT NULL,
	CONSTRAINT request_fk1 FOREIGN KEY (docID) REFERENCES Document(docID),
	CONSTRAINT request_fk2 FOREIGN KEY (CID) REFERENCES Company(CID),
	CONSTRAINT request_fk3 FOREIGN KEY (SID) REFERENCES Status(SID),
	CONSTRAINT request_pk PRIMARY KEY(docID)
);
CREATE TABLE ProjectRole (
	PRID	INTEGER,
	PRname		VARCHAR2(50),
	CONSTRAINT projectRole_pk PRIMARY KEY(PRID)
);
CREATE TABLE WorkerHasProjRole (
	docID	INTEGER,
	WID		INTEGER,
	PRID	INTEGER,
	CONSTRAINT worker_has_document_fk FOREIGN KEY (docID) REFERENCES Document(docID),
	CONSTRAINT worker_has_role_fk FOREIGN KEY (WID) REFERENCES Worker(WID),
	CONSTRAINT worker_has_worker_fk FOREIGN KEY (PRID) REFERENCES ProjectRole(PRID)
);
CREATE TABLE CheckOut (
	revID		INTEGER,
	WID		INTEGER,
	COID		INTEGER,
	COdate		DATE NOT NULL,
	CONSTRAINT checkOut_fk1 FOREIGN KEY (revID) REFERENCES Revision(revID),
	CONSTRAINT checkOut_fk2 FOREIGN KEY (WID) REFERENCES Worker(WID),
	CONSTRAINT checkOut_pk PRIMARY KEY(revID,WID)
);
CREATE TABLE CheckIn (
	revID		INTEGER,
	WID		INTEGER,
	CIID		INTEGER,
	CIdate		DATE NOT NULL,
	remarks		TEXT,
	CONSTRAINT checkIn_fk1 FOREIGN KEY (revID) REFERENCES Revision(revID),
	CONSTRAINT checkIn_fk2 FOREIGN KEY (WID) REFERENCES Worker(WID),
	CONSTRAINT checkIn_pk PRIMARY KEY(revID,WID)
);
CREATE TABLE Status (
	SID		INTEGER,
	sDescription	TEXT,
	CONSTRAINT status_pl PRIMARY KEY (SID)
);
